/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('./models/Arm.glb')
  return (
    // <group {...props} dispose={null}>
    //   <group position={[-0.005, 1.034, 0.024]} scale={0.2}>
    //     <mesh
    //       castShadow
    //       receiveShadow
    //       geometry={nodes.Plane004_1.geometry}
    //       material={materials.WhiteGloss}
    //     />
    //     <mesh
    //       castShadow
    //       receiveShadow
    //       geometry={nodes.Plane004_2.geometry}
    //       material={materials['metalic plate']}
    //     />
    //   </group>
    //   <group position={[0.204, 1.06, -0.248]} rotation={[-Math.PI / 2, 0, 0]} scale={0.069}>
    //     <primitive object={nodes.Bone} />
    //   </group>
    // </group>
    <group ref={group} {...props} dispose={null}>
    <group name="Scene">
      <group name="Robot_1" scale={0.189}>
        <mesh
          name="Plane004_1"
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={materials.WhiteGloss}
        />
        <mesh
          name="Plane004_2"
          castShadow
          receiveShadow
          geometry={nodes.Plane004_2.geometry}
          material={materials['metalic plate']}
        />
      </group>
      <group
        name="Armature"
        position={[-0.003, 1.246, -0.041]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.069}>
        <primitive object={nodes.Bone} />
      </group>
    </group>
  </group>
  )
}

useGLTF.preload('./models/Arm.glb')