// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function Model(props) {
//   const { nodes, materials } = useGLTF('./models/Arm.glb')
//   return (
//     <group {...props} dispose={null}>
//       <group rotation={[-Math.PI / 2, 0, 0]} scale={18.882}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane004_1.geometry}
//           material={materials.WhiteGloss}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane004_2.geometry}
//           material={materials['metalic plate']}
//         />
//       </group>
//       <group position={[-0.349, 124.556, -4.08]} rotation={[Math.PI, 0, 0]} scale={6.881}>
//         <group rotation={[Math.PI / 2, 0, 0]}>
//           <group position={[0.051, -0.593, -18.102]} scale={2.744}>
//             <mesh
//               castShadow
//               receiveShadow
//               geometry={nodes.Plane016.geometry}
//               material={materials.WhiteGloss}
//             />
//             <mesh
//               castShadow
//               receiveShadow
//               geometry={nodes.Plane016_1.geometry}
//               material={materials.BlueLight}
//             />
//           </group>
//           <group position={[0, 1, 0]} rotation={[0, 0, -1.582]}>
//             <group position={[1.589, 0.119, -18.102]} rotation={[0, 0, -1.527]} scale={2.744}>
//               <mesh
//                 castShadow
//                 receiveShadow
//                 geometry={nodes.Plane008.geometry}
//                 material={materials.WhiteGloss}
//               />
//               <mesh
//                 castShadow
//                 receiveShadow
//                 geometry={nodes.Plane008_1.geometry}
//                 material={materials['Rubber - Black.001']}
//               />
//             </group>
//             <group position={[0, 4.428, 0]} rotation={[0, 0, 2.142]}>
//               <group position={[-4.533, 0.739, -18.102]} rotation={[0, 0, -1.518]} scale={2.744}>
//                 <mesh
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Plane009_1.geometry}
//                   material={materials.WhiteGloss}
//                 />
//                 <mesh
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Plane009_2.geometry}
//                   material={materials['Rubber - Black.001']}
//                 />
//               </group>
//               <group position={[0, 4.206, 0]} rotation={[0, 0, -1.795]}>
//                 <group
//                   position={[4.112, -3.708, -18.102]}
//                   rotation={[0, 0, -Math.PI / 2]}
//                   scale={1.688}>
//                   <mesh
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.Plane010.geometry}
//                     material={materials.WhiteGloss}
//                   />
//                   <mesh
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.Plane010_1.geometry}
//                     material={materials['metalic plate']}
//                   />
//                   <mesh
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.Plane010_2.geometry}
//                     material={materials['Rubber - Black.001']}
//                   />
//                 </group>
//               </group>
//             </group>
//           </group>
//         </group>
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('./models/Arm.glb')
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/Arm.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.005, 1.034, 0.024]} scale={0.189}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={materials.WhiteGloss}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_2.geometry}
          material={materials['metalic plate']}
        />
      </group>
      <group position={[0.204, 1.06, -0.248]} rotation={[-Math.PI / 2, 0, 0]} scale={0.069}>
        <primitive object={nodes.Bone} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/Arm.glb')