/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/Hotels.glb')
  return (
    <group {...props} dispose={null} position={[0,0,0]}>
      {/* <group rotation={[-Math.PI / 2, 0, 0]} scale={1}> */}
        <mesh
          
          // castShadow
          // receiveShadow
          geometry={nodes.Plane005.geometry}
          material={materials['iMeshh Metal Anisotropoc']}
        />
        <mesh
          // castShadow
          // receiveShadow
          geometry={nodes.Plane005_1.geometry}
          material={materials.RedMetal}
        />

        
      {/* </group> */}
    </group>
  )
}

useGLTF.preload('./models/Hotels.glb')
