/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { useModelContext } from '../../context/ModelContext';
import { useXR } from '@react-three/xr';

export default function Model(props) {

  const meshRef = useRef()
  const { nodes:tableNode } = useGLTF("./models/Table.glb");
  const tableBoundingBox = new THREE.Box3().setFromObject(tableNode.Plane002_3);
  const tableHeight = tableBoundingBox.max.y;
  const tableWidth = tableBoundingBox.max.x;
  const tableStartIndex = tableBoundingBox.min.x;

  const {currentInstrument, setCurrentInstrument, hotelSelected, setHotelSelected} = useModelContext()
  const [positionArr, setPositionArr] = useState([0.25]);
  const [zArr, setZArr] = useState([-0.4, -0.4, 0.45, 0.45]);
  const [xArr, setXArr] = useState([
    tableStartIndex + 1.7, tableStartIndex + 1.4+0.6+0.6,
    tableStartIndex + 1.7, tableStartIndex + 1.4+0.6+0.6]);

  const [visible, setVisible] = useState(false);
  const [positionSelected, setPositionSelected] = useState(null);

  const m0 = {
    position: 0,
  };
  const m1 = {
    position: 1,
  };
  const m2 = {
    position: 2,
  };
  const backupMeshes = [];
  const [meshes, setMeshes] = useState([]);

  // const addMesh = (position) => {
  //   const newMesh = {
  //     position: position,
  //     // geometry: shape
  //   };
  //   setMeshes((prevMeshes) => [...prevMeshes, newMesh]);
  //   // meshes.push(newMesh)
  //   console.log(meshes)
  // };

  const setPositions = () => {
  let totalItemsOnTop = 9;
    let arr = [];
    arr.push(tableStartIndex + 1.59);
    for (let i = 0; i < totalItemsOnTop; i++) {
      arr.push(arr[i - 1] + 0.6);
    }
    setPositionArr(arr);
  };

  useEffect(() => {
    setPositions();
  }, []);

// useEffect(()=>{
//   setVisible(!visible)
//   // console.log(hotelSelected)
// },[hotelSelected, setHotelSelected])

 const placeHotel = async (index) => {
  // if(visible){
    // setVisible(false)
    // addMesh(index);
    const newMesh = {
      position: index,
    }
    // backupMeshes.push(newMesh);
    // console.log(backupMeshes)
    setMeshes((prevMeshes) => [...prevMeshes, newMesh]);
    setHotelSelected(false);
  // }
}

 const HotelModel = ({positions}) => {
  return(
   <group {...props} dispose={null} position={[positions[0], positions[1], positions[2]]} scale={0.4}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005.geometry}
          material={materials['iMeshh Metal Anisotropoc']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_1.geometry}
          material={materials.RedMetal}
        />
    </group>
  )
 }

 const checkIfModelPresent = () => {
  for(let i=0; meshes.length; i++){
    for(let j=0; j<meshes.length; j++){
      if(meshes.length){
      console.log(meshes[i])}
    // if(i === meshes[j].position){
      // return true;
      // console.log('first')
    // }
  }
 }
 return false;
}
// const x = checkIfModelPresent();
// useEffect(() => {
//   if(meshes.length){
//   console.log(checkIfModelPresent())
// }
// },[meshes.length])

  const { nodes, materials } = useGLTF('./models/Hotels.glb')
  return (
    <>
        {hotelSelected && positionArr.map((val, index) => {
            return (
              <mesh
                // visible={()=>checkIfModelPresent()}
                key={index}
                ref={meshRef}
                onClick={()=>placeHotel(index)}
                position={[xArr[index], tableHeight/2.5, zArr[index]]}
              >
                <boxGeometry args={[0.7, 0.001, 0.7]} />
                <meshStandardMaterial color={0x2c9e93} transparent={true} opacity={0.4}/>
              </mesh>
            );
          })}
          {meshes.map((mesh, index) =>{ return (
            <mesh key={index} >
              <HotelModel positions={[xArr[mesh.position], 0, zArr[mesh.position]]}/>
            </mesh>
          )})}
    </>
  )
}

useGLTF.preload('./models/Hotels.glb')








