/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/Lamp.glb')
  console.log(nodes)
  return (
    <group {...props} dispose={null} position={[0, 0, -4]} >
      {/* <group position={[132.697, 89.059, -49.74]} rotation={[-Math.PI / 2, 0, 0]} scale={18.882}> */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011.geometry}
          material={materials['metalic plate']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_1.geometry}
          material={materials.WhiteGloss}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_2.geometry}
          material={materials.Green}
        />
      {/* </group> */}
    </group>
  )
}

useGLTF.preload('./models/Lamp.glb')
