/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/PC.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet033.geometry}
          material={materials['metalic plate.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet033_1.geometry}
          material={materials['WhiteGloss.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet033_2.geometry}
          material={materials['plastic black']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet033_3.geometry}
          material={materials.Keyboard}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet033_4.geometry}
          material={materials['Black Plastic']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet033_5.geometry}
          material={materials['BlueMetal.001']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/PC.glb')