/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Table.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useConfigurator } from '../context/Configurator'

import { Box } from './Box';

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/Table.gltf')

  const {legs} = useConfigurator();

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plate.geometry} material={materials.Plate} />
      {
        legs == 0 && (
          <>
            <mesh geometry={nodes.Legs01Left.geometry} material={materials.Metal} position={[-1.5, 0, 0]} />
            <mesh geometry={nodes.Legs01Right.geometry} material={materials.Metal} position={[1.5, 0, 0]} />
          </>
        )
      }

      {
        legs == 1 && (
          <>
            <mesh geometry={nodes.Legs02Left.geometry} material={materials.Metal} position={[-1.5, 0, 0]} />
            <mesh geometry={nodes.Legs02Right.geometry} material={materials.Metal} position={[1.5, 0, 0]} />
          </>
        )
      }

      {
        legs == 2 && (
          <>
            <mesh geometry={nodes.Legs03Left.geometry} material={materials.Metal} position={[-1.5, 0, 0]} />
            <mesh geometry={nodes.Legs03Right.geometry} material={materials.Metal} position={[1.5, 0, 0]} />
          </>
        )
      }
      <Box/>

    </group>
  )
}

useGLTF.preload('./models/Table.gltf')
